### ISSUE TITLE
Toggle broken

### ISSUE THREAD

**Issue by jwbowles** [suan/libLGTV_serial#2]
Great job on this! I noticed that the toggle commands are only performing the first command of the two provided commands. I would be happy to help troubleshoot this

**Comment by suan** [comment]
Hmmm I believe its working for me. Could you be more specific? Which of the toggles are broken for you? Do any of them work? Whats the code you used to set them? Whats your TV model? The more info I have the easier it will be to debug :smiley:

**Comment by jwbowles** [comment]
Both the power and input toggles in your examples are not working for me.  I went ahead and downloaded your original examples and code from here and I'm printing out the command that is returned from the toggle function and it always stays on the poweron command.  I just kept the TV model on what you have it on in the example (42LK450) just to verify that it was working there, but I had no luck.  Thanks for the help! This is a great little library :)

**Comment by jwbowles** [comment]
So I did a bit more looking into and I noticed that the
self.query_data(command) query in the toggle function is returning an
empty string from my TV.  I'm not sure I fully understand how this
code is working, but I think that may be part of the issue.  For what
it's worth I'm trying to get this working on the M3201C model.  Here
is a link to the manual:
http://www.lg.com/us/support-product/lg-M3201C-BA
I had to add another reverse_code_map entry for my type of TV and
added another set of actual_codes for my TV and all the commands work
great individually just not the toggles.  Thanks again for the help!

On Wed, Mar 21, 2012 at 11:40 PM, suan
reply@reply.github.com
wrote:

**Comment by suan** [comment]
Interesting... your model is more like a monitor than a TV. So I looked through the manual, and the power command is in exactly the same format as the other models, but then I noticed what I think is the problem - unlike all the other manuals I've seen so far, yours specifies that you should use a "straight-through" serial cable rather than a "crossover" one.

This probably explains why you can send commands to the TV fine, but the toggle commands (which rely on first reading the current status from the TV) fail.

Try using a straight-through cable and I bet it'll work. In the meantime I'll update the code to properly support your model.

**Comment by jwbowles** [comment]
Ya it's a commercial grade display monitor usually used in stores as
signage. I'm actually using a USB to RS232 cable which are notoriously
problematic for receiving responses from devices so maybe I'll try a
different cable, but unfortunately I don't have any COM ports on my
home theater pc so it has to be another usb to serial cable.  Thanks
for all the help!

On Thu, Mar 22, 2012 at 6:55 PM, suan
reply@reply.github.com
wrote:

**Comment by suan** [comment]
No problem. Actually I think you may be able to get away with getting a straight through serial cable and putting that in between your USB-serial and TV. Don't quote me on it though!

**Comment by suan** [comment]
I've updated the code to support the M-series models. Pull down the latest version and let me know whether it works for you (barring the toggle issues)

**Comment by jwbowles** [comment]
It works great. I ordered a new cable so hopefully the toggle will start
working then. Thanks again for the great script!
On Mar 22, 2012 9:09 PM, "suan" <
reply@reply.github.com>
wrote:

**Comment by suan** [comment]
Closing this as I assume its working for you now with your new cable? Feel free to reopen if its still broken.
